### ISSUE TITLE
Bootstrap modal footer hides dropdown menu

### ISSUE THREAD

**Issue by michalmoravek** [jdewit/bootstrap-timepicker#104] opened 2013-03-21 16:24 UTC
I'm using bootstrap 2.3.0 and the newest timepicker, but I have problem with showing timepicker dropdown in modal window - it is showed under modal footer.
![timepicker](https://f.cloud.github.com/assets/3875243/286225/3266238c-9237-11e2-80be-a4f1ee94100f.jpg)

**Comment by michaelahlers** [comment] 2013-04-10 20:41
Running into this problem, too. Using 0.2.3.

**Comment by 5im0n** [comment] 2013-04-26 09:52
Got the same problem.
I think the Timepicker should be create out of the modal.

**Comment by michaelahlers** [comment] 2013-04-26 12:54
Append the element to the body?

**Comment by 5im0n** [comment] 2013-04-26 13:45
Yes, because the problem isn't due to a z-index.
For instance the plugin Bootstrap datepicker create calendar in the body.
http://www.eyecon.ro/bootstrap-datepicker/

**Comment by jtmille3** [comment] 2013-05-12 13:32
+1

**Comment by paultregoing** [comment] 2013-09-18 19:33
You can probably work around it by adding "overflow-y: visible" to .modal-body

**Comment by 5im0n** [comment] 2013-09-19 19:35
The problem is solved with Bootstrap 3 Modal

**Comment by jdewit** [comment] 2013-10-03 06:29
I'm in the process of updating to bs3.0. Closing this since it will no longer be an issue with 3.0.

**Closed as completed by jdewit** 2013-10-03 06:29 UTC
