### ISSUE TITLE
Leading zero in time value

### ISSUE THREAD

**Issue by alisabzevari** [jdewit/bootstrap-timepicker#323] opened 2016-01-10 07:39 UTC
Is there any way to add leading zero to time?
For example: 1:30 => 01:30

**Comment by mrhota** [comment] 2016-03-18 22:25
Not currently, but I would love to support it. Dupe of #203 

Truly, this would be supported implicitly if we internationalize the timepicker. I'm short on time.

**Closed as completed** 2016-03-18 22:26 UTC
Labels: duplicate

**Comment by juande32** [comment] 2018-10-29 12:09
You can solve this by editing the following functions in the original code:

`decrementHour: function() {
      
      /* Added this line at the end*/
      if (this.hour < 10) {this.hour = "0" + this.hour;}

    },




    incrementHour: function() {

      /* Added this line at the end */
      if (this.hour < 10) {this.hour = "0" + this.hour;}
    },`



    setTime: function(time, ignoreWidget) {

     /* Added this line at the end */
      if (hour < 10) {hour = "0" + hour;}

      this.hour = hour;
      this.minute = minute;
      this.second = second;
      this.meridian = meridian;

      this.update(ignoreWidget);
    },`

**Comment by MuhammadAlfadinSalim** [comment] 2020-02-05 09:41
just an addition for **juande32** answers 
change part in `incrementHour: function() {`
from: 
```
if (this.hour === this.maxHours - 1) {
        this.hour = 0;                  

        return;
      } 
```
to:
```
if (this.hour === this.maxHours - 1) {
        this.hour = "0"+0;                  

        return;
      }
```
